# Generated by Django 2.2.6 on 2019-11-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='body',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='current',
            field=models.BooleanField(default=True),
        ),
    ]
